FROM node:16-alpine AS development

WORKDIR /app

COPY package.json .
RUN echo "________________ RUNNING ECHO FROM DOCKER FILE"
RUN npm install

COPY . /app

ENV CI=true
ENV PORT=8089

CMD ["npm", "run", "start"]
